apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: fastapi-boilerplate
spec:
  selector:
    app: fastapi-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP # 내부 통신용 (External IP는 Ingress 등으로 관리 권장)
