"""add_department_code_and_usergroups

Revision ID: 0e117b5df651
Revises: ef66673e6c7b
Create Date: 2026-04-27 04:24:16.000811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e117b5df651'
down_revision: Union[str, None] = 'ef66673e6c7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
