"""rename_site_code_to_site

Revision ID: 586865ec5afd
Revises: 0e117b5df651
Create Date: 2026-04-29 04:29:50.790363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '586865ec5afd'
down_revision: Union[str, None] = '0e117b5df651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_dashboards',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('superset_dashboard_id', sa.Integer(), nullable=False),
    sa.Column('is_customized', sa.Boolean(), nullable=False),
    sa.Column('dashboard_title', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.alter_column('users', 'site_code', new_column_name='site')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'site', new_column_name='site_code')
    op.drop_table('user_dashboards')
    # ### end Alembic commands ###
