"""Add HMG SSO UserGroup and User models

Revision ID: d141e5936044
Revises: 7e14272ce7b5
Create Date: 2026-04-24 02:29:57.061811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd141e5936044'
down_revision: Union[str, None] = '7e14272ce7b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_groups',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('whitelisted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_groups_code'), 'user_groups', ['code'], unique=True)
    op.add_column('users', sa.Column('employee_id', sa.String(length=255), server_default='UNKNOWN', nullable=False))
    op.add_column('users', sa.Column('department', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('site_code', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.Enum('SUPERADMIN', 'ADMIN', 'USER', 'PERMISSION_REQUESTED', 'PERMISSION_REQUIRED', name='user_role', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'user'::character varying"))
    op.drop_constraint(op.f('ix_user_provider_social_id'), 'users', type_='unique')
    op.create_index(op.f('ix_users_employee_id'), 'users', ['employee_id'], unique=True)
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'provider')
    op.drop_column('users', 'social_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('social_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('provider', sa.VARCHAR(length=50), server_default=sa.text("'local'::character varying"), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_employee_id'), table_name='users')
    op.create_unique_constraint(op.f('ix_user_provider_social_id'), 'users', ['provider', 'social_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('SUPERADMIN', 'ADMIN', 'USER', 'PERMISSION_REQUESTED', 'PERMISSION_REQUIRED', name='user_role', native_enum=False),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False,
               existing_server_default=sa.text("'user'::character varying"))
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'site_code')
    op.drop_column('users', 'department')
    op.drop_column('users', 'employee_id')
    op.drop_index(op.f('ix_user_groups_code'), table_name='user_groups')
    op.drop_table('user_groups')
    # ### end Alembic commands ###
