"""add department_code to user

Revision ID: ef66673e6c7b
Revises: d141e5936044
Create Date: 2026-04-27 04:15:11.116247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef66673e6c7b'
down_revision: Union[str, None] = 'd141e5936044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('department_code', sa.String(length=100), nullable=True))
    op.alter_column('users', 'department',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.create_index(op.f('ix_users_department_code'), 'users', ['department_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_department_code'), table_name='users')
    op.alter_column('users', 'department',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('users', 'department_code')
    # ### end Alembic commands ###
